// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/backend.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackendRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RoomId          string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MessageType     uint32                 `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	RequestId       string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload         []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,7,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BackendRequest) Reset() {
	*x = BackendRequest{}
	mi := &file_api_proto_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendRequest) ProtoMessage() {}

func (x *BackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendRequest.ProtoReflect.Descriptor instead.
func (*BackendRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_backend_proto_rawDescGZIP(), []int{0}
}

func (x *BackendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BackendRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BackendRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BackendRequest) GetMessageType() uint32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *BackendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BackendRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BackendRequest) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type BackendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   uint32                 `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendResponse) Reset() {
	*x = BackendResponse{}
	mi := &file_api_proto_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendResponse) ProtoMessage() {}

func (x *BackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendResponse.ProtoReflect.Descriptor instead.
func (*BackendResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_backend_proto_rawDescGZIP(), []int{1}
}

func (x *BackendResponse) GetMessageType() uint32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *BackendResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BackendResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_api_proto_backend_proto protoreflect.FileDescriptor

const file_api_proto_backend_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/backend.proto\x12\x16gamegateway.backend.v1\"\xe9\x01\n" +
	"\x0eBackendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\rR\vmessageType\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12*\n" +
	"\x11timestamp_unix_ms\x18\a \x01(\x03R\x0ftimestampUnixMs\"m\n" +
	"\x0fBackendResponse\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\rR\vmessageType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode2k\n" +
	"\x0eBackendService\x12Y\n" +
	"\x06Handle\x12&.gamegateway.backend.v1.BackendRequest\x1a'.gamegateway.backend.v1.BackendResponseB\"Z game-gateway/api/proto;gatewayv1b\x06proto3"

var (
	file_api_proto_backend_proto_rawDescOnce sync.Once
	file_api_proto_backend_proto_rawDescData []byte
)

func file_api_proto_backend_proto_rawDescGZIP() []byte {
	file_api_proto_backend_proto_rawDescOnce.Do(func() {
		file_api_proto_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_backend_proto_rawDesc), len(file_api_proto_backend_proto_rawDesc)))
	})
	return file_api_proto_backend_proto_rawDescData
}

var file_api_proto_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_backend_proto_goTypes = []any{
	(*BackendRequest)(nil),  // 0: gamegateway.backend.v1.BackendRequest
	(*BackendResponse)(nil), // 1: gamegateway.backend.v1.BackendResponse
}
var file_api_proto_backend_proto_depIdxs = []int32{
	0, // 0: gamegateway.backend.v1.BackendService.Handle:input_type -> gamegateway.backend.v1.BackendRequest
	1, // 1: gamegateway.backend.v1.BackendService.Handle:output_type -> gamegateway.backend.v1.BackendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_backend_proto_init() }
func file_api_proto_backend_proto_init() {
	if File_api_proto_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_backend_proto_rawDesc), len(file_api_proto_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_backend_proto_goTypes,
		DependencyIndexes: file_api_proto_backend_proto_depIdxs,
		MessageInfos:      file_api_proto_backend_proto_msgTypes,
	}.Build()
	File_api_proto_backend_proto = out.File
	file_api_proto_backend_proto_goTypes = nil
	file_api_proto_backend_proto_depIdxs = nil
}
